name       : plasma-pa
version    : 5.14.1
release    : 27
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.1/plasma-pa-5.14.1.tar.xz : d83776d1a7da2c82e3bab20994a73713af1169f956f2da3583b962bdd82446b5
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
