name       : plasma-pa
version    : 5.11.4
release    : 10
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.4/plasma-pa-5.11.4.tar.xz : 7c5d2ca8797cb5b901c3fed1fa4a1b3aeaaa9d87c0d1108779b12f377427e37d
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gl)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - plasma-framework-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
