name       : plasma-pa
version    : 5.23.0
release    : 72
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.0/plasma-pa-5.23.0.tar.xz : 0044353d5ee41d948ec19263fb359660e1525b08ed279bc642b9659597331cb4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
libsplit   : no
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kirigami2-devel
    - knotifications-devel
    - plasma-framework-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc/HTML
