name       : plasma-pa
version    : 5.20.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.3/plasma-pa-5.20.3.tar.xz : 626de3f2b217ee3b62e896691e8551e393673a60892ed040b422e2da674fb1ca
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - knotifications-devel
    - plasma-framework-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc/HTML
