name       : plasma-pa
version    : 5.26.5
release    : 86
source     :
    - https://cdn.download.kde.org/stable/plasma/5.26.5/plasma-pa-5.26.5.tar.xz : 0582c5dc260ff51540d15e71d1ce82d9c439fd4d57e5bb69d4c8fc28d58d29a6
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
libsplit   : no
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - kcmutils-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kirigami2-devel
    - knotifications-devel
    - plasma-framework-devel
rundeps    :
    - kirigami2
    - sound-theme-freedesktop
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc/HTML
