name       : plasma-pa
version    : 5.23.4
release    : 76
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.4/plasma-pa-5.23.4.tar.xz : 4701dc362e615d321c1cc7b94240ab5b23898d7db8ec1a4ed49d84ac8907983c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
libsplit   : no
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kirigami2-devel
    - knotifications-devel
    - plasma-framework-devel
rundeps    :
    - kirigami2
    - sound-theme-freedesktop
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc/HTML
