name       : plasma-pa
version    : 5.11.1
release    : 7
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/plasma-pa-5.11.1.tar.xz : 8c741b1867131c7e23cbc8bd2f5fed69e4f224dd4ddc60ef95c632dec82ea63c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
libsplit   : no
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gl)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - plasma-framework-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
