name       : plasma-pa
version    : 5.11.2
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.2/plasma-pa-5.11.2.tar.xz : c84a4758fb5dab86df1b32660d66b37d21b7f1e450bd539959c3170f272373b2
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
libsplit   : no
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gl)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - plasma-framework-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
