name       : plasma-pa
version    : 5.21.1
release    : 63
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.1/plasma-pa-5.21.1.tar.xz : 396ed88423c9ef8cd6c2ea65425d6387f7cd2224698f29c434048f18f3de7d9f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
libsplit   : no
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kirigami2-devel
    - knotifications-devel
    - plasma-framework-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc/HTML
